#ifndef LITTLE_STAR_H__
#define LITTLE_STAR_H__

#include "Buzzer_def.h"

#define LITTLE_STAR_STANDARD	BUZZER_C_MAJOR_OFFSET
#define LITTLE_STAR_BPM			120

int16_t little_star_score[96]={
	BUZZER_DO_OFFSET,80,
	BUZZER_DO_OFFSET,80,
	BUZZER_SO_OFFSET,80,
	BUZZER_SO_OFFSET,80,
	BUZZER_LA_OFFSET,80,
	BUZZER_LA_OFFSET,80,
	BUZZER_SO_OFFSET,100,
	BUZZER_SO_OFFSET,80,
	
	BUZZER_FA_OFFSET,80,
	BUZZER_FA_OFFSET,80,
	BUZZER_MI_OFFSET,80,
	BUZZER_MI_OFFSET,80,
	BUZZER_RE_OFFSET,80,
	BUZZER_RE_OFFSET,80,
	BUZZER_DO_OFFSET,100,
	BUZZER_DO_OFFSET,80,
	
	BUZZER_SO_OFFSET,80,
	BUZZER_SO_OFFSET,80,
	BUZZER_FA_OFFSET,80,
	BUZZER_FA_OFFSET,80,
	BUZZER_MI_OFFSET,80,
	BUZZER_MI_OFFSET,80,
	BUZZER_RE_OFFSET,100,
	BUZZER_RE_OFFSET,80,
	
	BUZZER_SO_OFFSET,80,
	BUZZER_SO_OFFSET,80,
	BUZZER_FA_OFFSET,80,
	BUZZER_FA_OFFSET,80,
	BUZZER_MI_OFFSET,80,
	BUZZER_MI_OFFSET,80,
	BUZZER_RE_OFFSET,100,
	BUZZER_RE_OFFSET,80,
	
	BUZZER_DO_OFFSET,80,
	BUZZER_DO_OFFSET,80,
	BUZZER_SO_OFFSET,80,
	BUZZER_SO_OFFSET,80,
	BUZZER_LA_OFFSET,80,
	BUZZER_LA_OFFSET,80,
	BUZZER_SO_OFFSET,100,
	BUZZER_SO_OFFSET,80,
	
	BUZZER_FA_OFFSET,80,
	BUZZER_FA_OFFSET,80,
	BUZZER_MI_OFFSET,80,
	BUZZER_MI_OFFSET,80,
	BUZZER_RE_OFFSET,80,
	BUZZER_RE_OFFSET,80,
	BUZZER_DO_OFFSET,100,
	BUZZER_DO_OFFSET,80,
};


#endif 